name: .NET Core build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    steps:
    - name: Where
      run: pwd

    steps:
    - name: What
      run: ls -a

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore ./src/Polytext.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore ./src

    - name: Test
      run: dotnet test --no-restore --verbosity normal ./src

    - name: Publish on version change
      id: publish_nuget
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ./src/Polytext/Polytext.csproj
        VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
        TAG_COMMIT: true
        TAG_FORMAT: v*
        NUGET_KEY: ${{secrets.NUGETKEY}}
        NUGET_SOURCE: https://api.nuget.org
        INCLUDE_SYMBOLS: true